version: "3.8"

services:
  web:
    build: ./nginx
    volumes:
      - ../backend:/work/backend
      - php-fpm-socket:/var/run/php-fpm
    ports:
      - 80:80

  app:
    build: ./php
    volumes:
      - ../backend:/work/backend
      - php-fpm-socket:/var/run/php-fpm

  db:
    build: ./mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  php-fpm-socket:
  db-store:
