version: "3.8"

services:
  web:
    build: ./nginx
    volumes:
      - ../backend:/work/backend
      - php-fpm-socket:/var/run/php-fpm
    ports:
      - 80:80
      - 443:443

  app:
    build: ./php
    volumes:
      - ../backend:/work/backend
      - php-fpm-socket:/var/run/php-fpm

  composer:
    build: ./composer
    volumes:
      - ../backend:/work/backend

  worker:
    build: ./worker
    volumes:
      - ../backend:/work/backend

  db:
    build: ./mysql
    volumes:
      - db-store:/var/lib/mysql

  node:
    build: ./node
    volumes:
      - ../backend:/work/backend

volumes:
  php-fpm-socket:
  db-store:
