version: "3.8"

services:
  web:
    build: ./services/web
    volumes:
      - ../backend:/work/backend
      - php-fpm-socket:/var/run/php-fpm
    ports:
      - 80:80
      - 443:443

  fpm:
    build: ./services/fpm
    volumes:
      - ../backend:/work/backend
      - php-fpm-socket:/var/run/php-fpm

  composer:
    build: ./services/composer
    volumes:
      - ../backend:/work/backend

  worker:
    build: ./services/worker
    init: true
    volumes:
      - ../backend:/work/backend

  scheduler:
    build: ./services/scheduler
    init: true
    volumes:
      - ../backend:/work/backend

  db:
    build: ./services/db
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306

  node:
    build: ./services/node
    volumes:
      - ../backend:/work/backend

  socket:
    build: ./services/socket
    ports:
      - 6001:6001

  redis:
    build: ./services/redis

volumes:
  php-fpm-socket:
  db-store:
