version: "3.8"

services:
  web:
    build: ./nginx
    volumes:
      - ../backend:/work/backend
      - php-fpm-socket:/var/run/php-fpm
    ports:
      - "8080:80"

  app:
    build: ./php
    volumes:
      - ../backend:/work/backend
      - php-fpm-socket:/var/run/php-fpm

volumes:
  php-fpm-socket:
    name: php-fpm-socket
    driver: local
